version: "3.3"

services:
  postgres:
    build: .
    container_name: treatment_chart_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - treatment_chart_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  treatment_chart_data:
